#!/usr/bin/env python3
# Emit the per-file runner from file_classification.yaml.
#
# One pytest invocation per RUN file. DROP files are NOT in the runner —
# they're documented in file_classification.yaml's `drop` section and the
# parser/report surfaces them from there.
#
# Output: snapshots/bh_sanity/run_perfile.sh
#   - One emitted line per RUN file
#   - $OUT/<file-slug>.xml + $OUT/<file-slug>.log per file
#   - ONLY_FILE=<rel-path> env var skips all but one file (for ad-hoc retry)
#   - ONLY=<entry-slug> filters to files in that entry (for per-entry checkpoint)

import re
import sys
from pathlib import Path

import yaml

CLASSIFICATION = Path("/localdev/arminale/tt-emule/snapshots/bh_sanity/file_classification.yaml")
OUT_DIR = Path("/localdev/arminale/tt-emule/snapshots/bh_sanity")
RUNNER_PATH = OUT_DIR / "run_perfile.sh"
VARIANT_LABEL = "bh_emule"
PER_FILE_WALLCLOCK = 1350  # seconds — cap for one file's whole-run (bumped 50% from 900)
PER_TEST_TIMEOUT = 300     # seconds — pytest-timeout per-test (matches manifest's heaviest)
USE_FORKED = False         # `--forked` is intra-file isolation. Each file is already its
                           # own pytest process, so we get inter-file isolation for free.
                           # Dropping --forked saves ~0.3s/test × ~40k tests ≈ 3h.
                           # Cost: a segfault in one test crashes its pytest → no XML for
                           # that file. The parser's truncation detection picks those up
                           # for a targeted re-run with USE_FORKED=True on the next pass.


def slug(s: str) -> str:
    """Slugify a path or name. test_foo.py → test_foo; tests/.../test_bar.py → tests-...-test_bar"""
    s = s.removesuffix(".py")
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


def main():
    with CLASSIFICATION.open() as f:
        cls = yaml.safe_load(f)

    run_files = cls.get("run", [])
    drop_files = cls.get("drop", [])

    lines = [
        "#!/usr/bin/env bash",
        "# AUTOGENERATED by snapshots/bh_sanity/generate_perfile.py — do not edit.",
        "#",
        "# Per-file BH post-commit sweep. One pytest invocation per RUN file from",
        "# file_classification.yaml (the pre-filter classifier already excluded",
        "# files whose imports fail in the toolchain venv).",
        "#",
        "# Re-derive with: snapshots/bh_sanity/generate_perfile.py",
        "",
        "set -uo pipefail",
        "",
        ': "${CLUSTER_EXAMPLES:?CLUSTER_EXAMPLES must point at cluster_descriptor_examples}"',
        ': "${TT_METAL_HOME:?TT_METAL_HOME must be set}"',
        f'OUT="{OUT_DIR}/{VARIANT_LABEL}"',
        'mkdir -p "$OUT"',
        "",
        f'TOTAL={len(run_files)}',
        'COUNT=0',
        '',
    ]

    for r in run_files:
        rel = r["file"]
        file_slug = slug(rel)
        entries = ",".join(r.get("entries") or [])

        # Per-entry filter: if ONLY is set, run only files whose entry list includes it
        only_match = '||'.join([f'[ "$ONLY" = "{e}" ]' for e in (r.get("entries") or [])])
        if only_match:
            only_check = f'( {only_match} )'
        else:
            only_check = 'false'  # file has no entry — skip when ONLY set

        forked_flag = "--forked " if USE_FORKED else ""
        lines.append(f'if ! ( [ -z "${{ONLY:-}}" ] || {only_check} ); then :')
        lines.append(f'elif [ -n "${{ONLY_FILE:-}}" ] && [ "${{ONLY_FILE}}" != "{rel}" ]; then :')
        lines.append(f'elif [ -s "$OUT/{file_slug}.xml" ]; then')
        lines.append(f'  echo "skip: $OUT/{file_slug}.xml already exists ({rel})"')
        lines.append(f'else')
        lines.append(f'  COUNT=$((COUNT + 1))')
        lines.append(f'  echo "::group::[$COUNT/$TOTAL] {rel}"')
        lines.append(f'  echo "# entries: {entries}"')
        lines.append(
            f'  TT_METAL_EMULE_MODE=1 TT_METAL_SLOW_DISPATCH_MODE=1 '
            f'MESH_DEVICE=P100 TT_METAL_MOCK_CLUSTER_DESC_PATH=$CLUSTER_EXAMPLES/blackhole_P100.yaml '
            f'timeout {PER_FILE_WALLCLOCK} pytest {forked_flag}--timeout {PER_TEST_TIMEOUT} -v '
            f'-m "not disable_fast_runtime_mode" '
            f'{rel} '
            f'--junitxml=$OUT/{file_slug}.xml > $OUT/{file_slug}.log 2>&1'
        )
        lines.append(f'  rc=$?; echo "rc=$rc {rel}"')
        lines.append(f'  echo "::endgroup::"')
        lines.append(f'fi')
        lines.append('')

    RUNNER_PATH.write_text("\n".join(lines) + "\n")
    RUNNER_PATH.chmod(0o755)
    print(f"wrote {RUNNER_PATH}")
    print(f"emitted {len(run_files)} per-file invocations")
    print(f"dropped {len(drop_files)} files (in file_classification.yaml `drop` section)")


if __name__ == "__main__":
    main()
